#!/bin/bash

IP=$(ip addr | grep -Ev "^.*secondary.*$" | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -Ev ".*(255|1)$")
MASK=$(echo $IP | sed -En 's/\.[0-9]{1,3}$/.0\/24/p')
GATEWAY=$(echo $IP | sed -En 's/\.[0-9]{1,3}$/\.1/p')
INTERFACE=$(ip addr | grep -E "BROADCAST.*LOWER_UP" | grep -Eo "[0-9]+\: [a-z0-9]+" | cut -f2 -d ' ' | grep -Ev "^v.*$")

while getopts 'himgn' OPTION; do
  case "$OPTION" in
  h)
    echo "Usage: $0 [-h] [-i] [-m] [-g] [-n]" 
    echo "-h: help"
    echo "-i: ipv4 address"
    echo "-m: network mask"
    echo "-g: network gateway"
    echo "-n: network interface"
    ;;
  i)
    echo $IP
    ;;
  m)
    echo $MASK 
    ;;
  g)
    echo $GATEWAY
    ;;
  n)
    echo $INTERFACE
    ;;
  ?)
    echo "Usage: $0 [-h] [-i] [-m] [-g] [-n]" >&2
    exit 1
    ;;
  esac
done 

shift "$(($OPTIND -1))"
