- name: Copy modconfig.sh to server
  copy:
    src: modconfig
    dest: /usr/bin
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0500

- name: Harden sshd_config from https://node-security.com/posts/ssh-server-hardening/
  shell: |
    modconfig -p PubkeyAuthentication -v yes -f /etc/ssh/sshd_config
    modconfig -p PasswordAuthentication -v no -f /etc/ssh/sshd_config
    modconfig -p PermitEmptyPasswords -v no -f /etc/ssh/sshd_config
    modconfig -p PermitRootLogin -v no -f /etc/ssh/sshd_config
    modconfig -p AllowUsers -v "{{ ansible_user }}" -f /etc/ssh/sshd_config
    modconfig -p X11Forwarding -v no -f /etc/ssh/sshd_config
    modconfig -p GatewayPorts -v no -f /etc/ssh/sshd_config
    modconfig -p Ciphers -v aes256-gcm@openssh.com,aes256-ctr -f /etc/ssh/sshd_config
    modconfig -p KexAlgorithms -v curve25519-sha256@libssh.org,ecdh-sha2-nistp521 -f /etc/ssh/sshd_config
    modconfig -p MACs -v hmac-sha2-512-etm@openssh.com,hmac-sha2-512 -f /etc/ssh/sshd_config
    modconfig -p Protocol -v 2 -f /etc/ssh/sshd_config
    # modconfig -p PermitUserEnvironment -v no -f /etc/ssh/sshd_config

    # disable small Diffie-Hellman key sizes
    awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe
    mv /etc/ssh/moduli.safe /etc/ssh/moduli

- name: Restart ssh service
  systemd:
    name: ssh
    enabled: yes
    state: restarted
